import { Inter } from "next/font/google";

import { Header } from "./components/Header";
import "./globals.css";
import fsPromises from "fs/promises";
import path from "path";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Codedamn Assignment",
  description: "Generated by create next app",
};

const getData = async () => {
  const filePath = path.join(process.cwd(), "user.json");
  const jsonData = await fsPromises.readFile(filePath);
  const objectData = JSON.parse(jsonData);
  return objectData;
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await getData();
  console.log(data);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header notifications={1} imageUrl={data.imageUrl} level={data.level}/>
        {children}
      </body>
    </html>
  );
}
